# Generated by Django 6.0.1 on 2026-02-12 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('available_services', models.JSONField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('health_worker', 'Health Worker'), ('facility_admin', 'Facility Admin'), ('transport_officer', 'Transport_Officer'), ('system_admin', 'System Admin')], max_length=20),
        ),
        migrations.CreateModel(
            name='EmergencyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_age', models.IntegerField()),
                ('gestational_age', models.IntegerField()),
                ('danger_signs', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('ambulance', 'Ambulance'), ('motorbike', 'Motorbike'), ('car', 'Car'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('capacity', models.IntegerField(help_text='Number of patients that can be transported')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='core.healthfacility')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emergency_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emergencycase')),
                ('receiving_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_in', to='core.healthfacility')),
                ('referring_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_out', to='core.healthfacility')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transport')),
            ],
        ),
    ]
