# Generated by Django 6.0.2 on 2026-02-23 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_healthfacility_alter_user_role_emergencycase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE_CASE', 'Created Emergency Case'), ('SUGGEST_REFERRAL', 'Suggested Referral'), ('CREATE_REFERRAL', 'Created Referral'), ('ACCEPT_REFERRAL', 'Accepted Referral'), ('DISPATCH_REFERRAL', 'Dispatched Transport'), ('COMPLETE_REFERRAL', 'Completed Referral')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('emergency_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emergencycase')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.referral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
