# Generated by Django 6.0.1 on 2026-03-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emergencyalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pregnancy_risk_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
    ]
