# Generated by Django 6.0.1 on 2026-03-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_patient_pregnancy_risk_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthfacility',
            name='capacity',
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='facility_type',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Clinic', 'Clinic'), ('Health Center', 'Health Center')], default='Health Center', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
